# Generated by Django 5.1.2 on 2024-10-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmaster_app', '0009_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'PAID'), ('unpaid', 'UNPAID')], default='unpaid', max_length=100),
        ),
    ]
